# Generated by Django 4.2.9 on 2024-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('analog_input_count', models.IntegerField(blank=True, default=0, null=True)),
                ('analog_input_RTD_count', models.IntegerField(blank=True, default=0, null=True)),
                ('analog_output_count', models.IntegerField(blank=True, default=0, null=True)),
                ('discrete_input_count', models.IntegerField(blank=True, default=0, null=True)),
                ('discrete_output_count', models.IntegerField(blank=True, default=0, null=True)),
                ('pneumatic_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
